Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCFinApp.Data;
using MVCFinApp.Models;

namespace MVCFinApp.Controllers
{
    [Authorize]
    public class BankAccountsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<FAUser> _userManager;

        public BankAccountsController(ApplicationDbContext context, UserManager<FAUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize(Roles = "Administrator,Head,Member")]
        // GET: BankAccounts
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var applicationDbContext = _context.BankAccount.Where(x => x.HouseHoldId == user.HouseHoldId).Include(b => b.HouseHold).Include(u => u.FAUser);
            return View(await applicationDbContext.ToListAsync());
        }

        [Authorize(Roles = "Administrator,Head,Member")]
        // GET: BankAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            var bankAccount = await _context.BankAccount
                .Include(b => b.HouseHold)
                .FirstOrDefaultAsync(x => x.HouseHoldId == user.HouseHoldId && x.Id == id);

            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        [Authorize(Roles = "Administrator,Head,Member")]
        // GET: BankAccounts/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            ViewData["HouseHoldId"] = user.HouseHoldId;
            return View();
        }

        // POST: BankAccounts/Create
        // To protect from over-posting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator,Head,Member")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,HouseHoldId,FPUserId,Name,Type,StartingBalance,CurrentBalance")] BankAccount bankAccount)
        {
            bankAccount.FAUserId = _userManager.GetUserId(User);
            bankAccount.CurrentBalance = bankAccount.StartingBalance;
            if (ModelState.IsValid)
            {
                _context.Add(bankAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction("Dashboard", "HouseHolds");
            }
            ViewData["HouseHoldId"] = new SelectList(_context.HouseHold, "Id", "Name", bankAccount.HouseHoldId);
            return View(bankAccount);
        }

        // GET: BankAccounts/Edit/5
        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            var bankAccount = await _context.BankAccount
                .FirstOrDefaultAsync(x => x.HouseHoldId == user.HouseHoldId && x.Id == id);
            if (bankAccount == null)
            {
                return NotFound();
            }
            ViewData["HouseHoldId"] = new SelectList(_context.HouseHold, "Id", "Name", bankAccount.HouseHoldId);
            return View(bankAccount);
        }

        // POST: BankAccounts/Edit/5
        // To protect from over-posting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator,Head,Member")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,HouseHoldId,FPUserId,Name,Type,StartingBalance,CurrentBalance")] BankAccount bankAccount)
        {
            if (id != bankAccount.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bankAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BankAccountExists(bankAccount.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HouseHoldId"] = new SelectList(_context.HouseHold, "Id", "Name", bankAccount.HouseHoldId);
            return View(bankAccount);
        }

        // GET: BankAccounts/Delete/5
        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            var bankAccount = await _context.BankAccount
                .FirstOrDefaultAsync(x => x.HouseHoldId == user.HouseHoldId && x.Id == id);
            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        // POST: BankAccounts/Delete/5
        [Authorize(Roles = "Administrator,Head,Member")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bankAccount = await _context.BankAccount.FindAsync(id);
            _context.BankAccount.Remove(bankAccount);
            await _context.SaveChangesAsync();
            return RedirectToAction("Dashboard", "HouseHolds");
        }

        private bool BankAccountExists(int id)
        {
            return _context.BankAccount.Any(e => e.Id == id);
        }
    }
}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCFinApp.Data;
using MVCFinApp.Models;

namespace MVCFinApp.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<FAUser> _userManager;

        public CategoriesController(ApplicationDbContext context, UserManager<FAUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Categories
        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var applicationDbContext = _context.Category
                .Where(x => x.HouseHoldId == user.HouseHoldId)
                .Include(c => c.HouseHold);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Categories/Details/5
        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            var category = await _context.Category
                .Include(c => c.HouseHold)
                .Where(x => x.HouseHoldId == user.HouseHoldId)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        [Authorize(Roles = "Administrator,Head,Member")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from over-posting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<IActionResult> Create([Bind("Id,HouseHoldId,Name,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                TempData["Script"] = $"NewColor('{category.Name}')";
                return RedirectToAction("Dashboard", "HouseHolds");
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            var category = await _context.Category
                .Where(x => x.HouseHoldId == user.HouseHoldId)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from over-posting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,HouseHoldId,Name,Description")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            var category = await _context.Category
                .Include(c => c.HouseHold)
                .Where(x => x.HouseHoldId == user.HouseHoldId)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_HouseholdModalPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="modal fade" id="householdModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">New household</h3>
            </div>
            <div class="modal-body">
                <form asp-controller="HouseHolds" asp-action="Create">
                    <div class="form-group">
                        <label for="Name" class="control-label">Name</label>
                        <input name="Name" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Greeting" class="control-label">Greeting</label>
                        <input name="Greeting" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Established" class="control-label" hidden></label>
                        <input type="hidden" name="Established" class="form-control" value="@DateTime.Now" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Shared/_InvitationCodePartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using Microsoft.AspNetCore.Identity
@inject UserManager<FAUser> UserManager
@{
    var user = await UserManager.GetUserAsync(User);
}
<div class="modal fade" id="invitationCodeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Accept invitation</h3>
            </div>
            <div class="modal-body">
                <form asp-controller="Invitations" asp-action="Accept" enctype="multipart/form-data" method="get">
                    <div class="form-group">
                        <input type="hidden" name="email" class="form-control" value="@user.Email" />
                    </div>
                    <div class="form-group">
                        <label for="code" style="color:#3b3f5c;">Code</label>
                        <input name="code" class="form-control" />
                    </div>
                    <div class="row justify-content-between">
                        <div class="col-md">
                            <button type="submit" class="btn btn-primary">Join</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
@using MVCFinApp.Data.Enums
@using Microsoft.AspNetCore.Identity
@inject UserManager<FAUser> UserManager
@{
    var user = await UserManager.GetUserAsync(User);
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Responsive Budget Application" />
    <meta name="author" content="SmartMoney" />
    <title>@ViewData["Title"] Smart Money</title>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" type="text/css" />

    <!-- icons -->
    <link href="~/fonts/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/fonts/material-design-icons/material-icon.css" rel="stylesheet" type="text/css" />

    <!--bootstrap -->
    <link href="~/plugins/bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Material Design Lite CSS -->
    <link href="~/plugins/material/material.min.css" rel="stylesheet" />
    <link href="~/css/material_style.css" rel="stylesheet" />

    <!-- Theme Styles -->
    <link href="~/css/theme/dark/theme_style.css" rel="stylesheet" id="rt_style_components" type="text/css" />
    <link href="~/css/theme/dark/theme_style.css" rel="stylesheet" type="text/css" />
    <link href="~/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/responsive.css" rel="stylesheet" type="text/css" />
    <link href="~/css/theme/dark/theme-color.css" rel="stylesheet" type="text/css" />

    <!-- favicon -->
    <link rel="shortcut icon" href="~/images/favicon.ico" />
</head>
<!-- END HEAD -->

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Smart Money</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        @if (User.IsInRole(nameof(Roles.Administrator)))
                        {
                            <li class="active">
                                <a  class="nav-link text-dark" asp-controller="HouseHolds" asp-action="Index"> All </a>
                            </li>
                        }
                        <li>
                            <a  class="nav-link text-dark" asp-controller="HouseHolds" asp-action="Dashboard"> Dashboard</a>
                        </li>
                        <li>
                            <a  class="nav-link text-dark" asp-controller="BankAccounts" asp-action="Index">Manage Accounts</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-controller="Categories" asp-action="Index">Manage Categories</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-controller="CategoryItems" asp-action="Index">Manage Items</a>
                        </li>
                        @if (User.IsInRole(nameof(Roles.Administrator)) || User.IsInRole(nameof(Roles.New)))
                        {
                            <li>
                                <a class="nav-link text-dark" asp-controller="HouseHolds" asp-action="Create"> Create</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div id="content" class="main-content">
        <div class="layout-px-spacing">
            @if (User.Identity.IsAuthenticated)
            {
                <div class="page-header" hidden>
                    <div class="page-title">
                        <h3>Role ---> @User.Claims</h3>
                    </div>
                    <div class="dropdown filter custom-dropdown-icon">
                        <a class="dropdown-toggle btn" href="#" role="button" id="filterDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="text"><span>Show</span> : Daily Analytics</span> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg></a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="filterDropdown">
                            <a class="dropdown-item" data-value="<span>Show</span> : Daily Analytics" href="javascript:void(0);">Daily Analytics</a>
                            <a class="dropdown-item" data-value="<span>Show</span> : Weekly Analytics" href="javascript:void(0);">Weekly Analytics</a>
                            <a class="dropdown-item" data-value="<span>Show</span> : Monthly Analytics" href="javascript:void(0);">Monthly Analytics</a>
                            <a class="dropdown-item" data-value="Download All" href="javascript:void(0);">Download All</a>
                            <a class="dropdown-item" data-value="Share Statistics" href="javascript:void(0);">Share Statistics</a>
                        </div>
                    </div>
                </div>
            }

            <main role="main">
                @RenderBody()
            </main>

        </div>
        @if (User.Identity.IsAuthenticated)
        {
            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2020 - Smart Money - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        }
    </div>

    <!-- start js include path -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/popper/popper.js"></script>
    <script src="~/plugins/jquery-blockui/jquery.blockui.min.js"></script>
    <script src="~/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- bootstrap -->
    <script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>

    <!-- Common js-->
    <script src="~/js/app.js"></script>
    <script src="~/js/layout.js"></script>
    <script src="~/js/theme-color.js"></script>

    <!-- Material -->
    <script src="~/plugins/material/material.min.js"></script>-->

    <!-- end js include path -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @*sweet alerts*@
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_NotificationPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@*@using Microsoft.AspNetCore.Identity
@inject MVCFinApp.Services.INotificationService _notificationService
@inject UserManager<FAUser>
    UserManager
    @{
    var user = await UserManager.GetUserAsync(User);
    var notifications = await _notificationService.GetNotificationsAsync(user.Id);
    }

    @if (notifications.Count > 0)
    {
    <li id="notificationBell" class="menu single-menu">
        <a href="#dashboard" data-toggle="collapse" aria-expanded="true" class="dropdown-toggle autodroprown">
            <div class="">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.73 21a2 2 0 0 1-3.46 0"></path></svg>
            </div>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
        </a>
        <ul class="collapse submenu list-unstyled" id="dashboard" data-parent="#topAccordion">
            <li>
                @foreach (var notification in notifications)
                {
                <a asp-controller="Notifications" asp-action="Details" asp-route-id="@notification.Id"> @notification.Subject </a>
                }
            </li>
        </ul>
    </li>
    }
    else
    {
    <li class="menu single-menu">
        <a>
            <div class="">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell-off"><path d="M13.73 21a2 2 0 0 1-3.46 0"></path><path d="M18.63 13A17.89 17.89 0 0 1 18 8"></path><path d="M6.26 6.26A5.86 5.86 0 0 0 6 8c0 7-3 9-3 9h14"></path><path d="M18 8a6 6 0 0 0-9.33-5"></path><line x1="1" y1="1" x2="23" y2="23"></line></svg>
            </div>
        </a>
    </li>
    }
}*@