Models/HouseHold.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVCFinApp.Models
{
    public class HouseHold
    {
        public int Id { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 2)]
        public string Name { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 2)]
        public string Greeting { get; set; }

        public DateTime Established { get; set; }

        public virtual ICollection<Attachment> Attachments { get; set; } = new HashSet<Attachment>();
        public virtual ICollection<Invitation> Invitations { get; set; } = new HashSet<Invitation>();
        public virtual ICollection<Notification> Notifications { get; set; } = new HashSet<Notification>();
        public virtual ICollection<Category> Categories { get; set; } = new HashSet<Category>();
        public virtual ICollection<BankAccount> BankAccounts { get; set; } = new HashSet<BankAccount>();
        public virtual ICollection<FAUser> FAUsers { get; set; } = new HashSet<FAUser>();
    }
}

Controllers/ChartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCFinApp.Data;
using MVCFinApp.Data.Enums;
using MVCFinApp.Models;
using MVCFinApp.Models.Charts;
using MVCFinApp.Services;

namespace MVCFinApp.Controllers
{
    [Authorize]
    public class ChartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<FAUser> _userManager;

        public ChartsController(ApplicationDbContext context, UserManager<FAUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<JsonResult> Categories()
        {
            var list = new List<BudgetPieChartData>();
            var user = await _userManager.GetUserAsync(User);
            var houseHold = await _context.HouseHold
                .Include(hh => hh.Categories).ThenInclude(c => c.CategoryItems)
                .FirstOrDefaultAsync(hh => hh.Id == user.HouseHoldId);

            foreach (var category in houseHold.Categories)
            {
                decimal total = 0;
                foreach (var item in category.CategoryItems)
                {
                    total += item.ActualAmount;
                }

                list.Add(
                new BudgetPieChartData
                {
                    Name = category.Name,
                    Total = total
                });
            }
            return Json(list);
        }

        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<JsonResult> Items()
        {
            var user = await _userManager.GetUserAsync(User);
            var houseHold = await _context.HouseHold.Include(hh => hh.Categories).ThenInclude(c => c.CategoryItems).FirstOrDefaultAsync(hh => hh.Id == user.HouseHoldId);
            var items = houseHold.Categories.SelectMany(c => c.CategoryItems).ToList();
            var list = new List<CategoryItemsBarChartData>();
            items.ForEach(item => list.Add(
                new CategoryItemsBarChartData
                {
                    Category = item.Category.Name,
                    Name = item.Name,
                    Goal = item.TargetAmount,
                    Reality = item.ActualAmount
                }
            ));
            return Json(list);
        }

        //[Authorize(Roles = "Administrator,Head,Member")]
        public async Task<JsonResult> History()
        {
            var user = await _userManager.GetUserAsync(User);
            var houseHold = await _context.HouseHold
                .Include(hh => hh.BankAccounts)
                .ThenInclude(ba => ba.Histories)
                .FirstOrDefaultAsync(hh => hh.Id == user.HouseHoldId);

            var lines = new List<Line>();
            var oldest = DateTime.Now;
            var newest = DateTime.Now;

            foreach (var account in houseHold.BankAccounts)
            {
                var line = new Line
                {
                    Name = account.Name,
                    Xcords = new List<string>(),
                    Ycords = new List<decimal>()
                };

                var histories = account.Histories.OrderBy(h => h.Date).ToList(); // oldest to newest
                foreach (var history in histories)
                {
                    oldest = UpdateOldestDate(history.Date, oldest);
                    newest = UpdateNewestDate(history.Date, newest);
                    var date = history.Date.ToString("MM/dd/yyyy");
                    line.Xcords.Add(date);
                    line.Ycords.Add(history.Balance);
                }

                lines.Add(line);
            }

            List<string> dates = PopulateDates(oldest, newest);
            var chart = new Chart
            {
                Dates = dates,
                Lines = lines
            };
            return Json(chart);
        }

        // start date
        private DateTime UpdateOldestDate(DateTime date, DateTime oldest)
        {
            if (date < oldest)
            {
                return date;
            }
            return oldest;
        }

        // end date
        private DateTime UpdateNewestDate(DateTime date, DateTime newest)
        {
            if (date > newest)
            {
                return date;
            }
            return newest;
        }

        // list from start to end
        private List<string> PopulateDates(DateTime oldest, DateTime newest)
        {
            var dates = new List<string>();
            while (oldest < newest)
            {
                dates.Add(oldest.ToString("MM/dd/yyyy"));
                oldest = oldest.AddDays(1);
            }
            dates.Add(newest.ToString("MM/dd/yyyy"));
            return dates.Distinct().ToList();
        }
    }
}

Controllers/HouseHoldsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCFinApp.Data;
using MVCFinApp.Data.Enums;
using MVCFinApp.Models;
using MVCFinApp.Models.ViewModels;
using MVCFinApp.Services;

namespace MVCFinApp.Controllers
{
    [Authorize]
    public class HouseHoldsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<FAUser> _userManager;
        private readonly SignInManager<FAUser> _signInManager;
        private readonly IHouseHoldService _houseHoldService;

        public HouseHoldsController(ApplicationDbContext context, UserManager<FAUser> userManager, SignInManager<FAUser> signInManager, IHouseHoldService houseHoldService)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _houseHoldService = houseHoldService;
        }

        // GET: HouseHolds
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.HouseHold.ToListAsync());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Join(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            user.HouseHoldId = id;
            var roles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, roles);
            await _userManager.AddToRoleAsync(user, Roles.Member.ToString());
            await _context.SaveChangesAsync();

            // sign out / sign in
            await _signInManager.RefreshSignInAsync(user);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Leave()
        {
            var user = await _userManager.GetUserAsync(User);

            if (User.IsInRole(Roles.Head.ToString()))
            {
                var members = await _houseHoldService.ListHouseHoldMembersAsync(user.HouseHoldId);
                if (members.Count > 0)
                {
                    TempData["Script"] = "CantLeave()";
                    return RedirectToAction("Dashboard");
                }
                // delete household
                var houseHold = await _context.HouseHold.FirstOrDefaultAsync(hh => hh.Id == user.HouseHoldId);
                _context.HouseHold.Remove(houseHold);
            }

            // not in a house
            user.HouseHoldId = null;

            // reset role to New
            var roles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, roles);
            await _userManager.AddToRoleAsync(user, Roles.New.ToString());
            await _context.SaveChangesAsync();

            // sign out / sign in
            await _signInManager.RefreshSignInAsync(user);
            return RedirectToAction("Index", "Home");
        }

        // GET: HouseHolds/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var houseHold = await _context.HouseHold
                .FirstOrDefaultAsync(m => m.Id == id);
            if (houseHold == null)
            {
                return NotFound();
            }

            return View(houseHold);
        }

        // GET: HouseHolds/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: HouseHolds/Create
        // To protect from over-posting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Greeting,Established")] HouseHold houseHold)
        {
            if (ModelState.IsValid)
            {
                _context.Add(houseHold);
                await _context.SaveChangesAsync();

                var user = await _userManager.GetUserAsync(User);
                user.HouseHoldId = houseHold.Id;

                var roles = await _userManager.GetRolesAsync(user);
                await _userManager.RemoveFromRolesAsync(user, roles);
                await _userManager.AddToRoleAsync(user, Roles.Head.ToString());
                await _context.SaveChangesAsync();

                // sign out / sign in
                await _signInManager.SignOutAsync();
                await _signInManager.SignInAsync(user, isPersistent: false);

                TempData["Script"] = "Wizard()";
                return RedirectToAction(nameof(Dashboard));
            }
            return View(houseHold);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetUp(string bank, AccountType accountType, decimal startBalance,
            string categoryName, string catDesc, string itemName, string itemDesc, decimal target)
        {
            var user = await _userManager.GetUserAsync(User);
            var bankAccount = new BankAccount
            {
                HouseHoldId = (int)user.HouseHoldId,
                FAUserId = user.Id,
                Name = bank,
                Type = accountType,
                StartingBalance = startBalance,
                CurrentBalance = startBalance
            };
            await _context.AddAsync(bankAccount);
            await _context.SaveChangesAsync();

            var category = new Category
            {
                HouseHoldId = (int)user.HouseHoldId,
                Name = categoryName,
                Description = catDesc
            };
            await _context.AddAsync(category);
            await _context.SaveChangesAsync();

            var item = new CategoryItem
            {
                CategoryId = category.Id,
                Name = itemName,
                Description = itemDesc,
                TargetAmount = target,
                ActualAmount = 0
            };
            await _context.AddAsync(item);
            await _context.SaveChangesAsync();

            return RedirectToAction("Dashboard");
        }

        [Authorize(Roles = "Administrator,Head,Member")]
        public async Task<IActionResult> Dashboard(string year, string month)
        {
            var user = await _userManager.GetUserAsync(User);
            var houseHold = await _context.HouseHold
                .Include(hh => hh.BankAccounts).ThenInclude(ba => ba.Transactions).ThenInclude(t => t.BankAccount)
                .Include(hh => hh.BankAccounts).ThenInclude(ba => ba.Transactions).ThenInclude(t => t.CategoryItem)
                .Include(hh => hh.BankAccounts).ThenInclude(ba => ba.Transactions).ThenInclude(t => t.FAUser)
                .FirstOrDefaultAsync(hh => hh.Id == user.HouseHoldId);

            var transactions = _houseHoldService.ListTransactions(houseHold);

            if (year != null)
            {   // DateTime.Parse needs a valid date-time format
                var _year = DateTime.Parse($"Jan 1, {year}").Year;
                transactions = transactions.Where(t => t.Created.Year == _year).ToList();
            }
            if (month != null)
            {   // DateTime.Parse needs a valid date-time format
                var _month = DateTime.Parse($"{month} 1, 2009").Month;
                transactions = transactions.Where(t => t.Created.Month == _month).ToList();
            }

            var model = new HHDashboardVM
            {
                Occupants = await _context.Users.Where(u => u.HouseHoldId == user.HouseHoldId).ToListAsync(),
                Accounts = houseHold.BankAccounts,
                Transactions = transactions
            };

            var categories = _context.Category
                .Include(c => c.CategoryItems)
                .Where(c => c.HouseHoldId == houseHold.Id).ToList();
            var items = new List<CategoryItem>();
            foreach (var category in categories)
            {
                foreach (var item in category.CategoryItems)
                {
                    items.Add(item);
                }
            }
            var bankAccounts = _context.BankAccount.Where(ba => ba.HouseHoldId == houseHold.Id).ToList();

            int oldestYear = int.Parse(_context.Transaction.OrderBy(t => t.Created).First().Created.Year.ToString());
            int currentYear = int.Parse(DateTime.Now.Year.ToString());
            var years = new List<string>();
            while (currentYear >= oldestYear)
            {
                years.Add(currentYear.ToString());
                currentYear -= 1;
            }
            var months = new List<string> { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" };
            ViewData["Years"] = new SelectList(years, year ?? DateTime.Now.Year.ToString());
            ViewData["Months"] = new SelectList(months, month ?? DateTime.Now.Month.ToString());

            ViewData["CategoryId"] = new SelectList(categories, "Id", "Name");
            ViewData["BankAccountId"] = new SelectList(bankAccounts, "Id", "Name");
            ViewData["CategoryItemId"] = new SelectList(items, "Id", "Name");

            return View(model);
        }

        // GET: HouseHolds/Edit/5
        [Authorize(Roles = "Administrator,Head")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var houseHold = await _context.HouseHold.FindAsync(id);

Views/HouseHolds/Create.cshtml
@model MVCFinApp.Models.HouseHold

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-md mt-3">
        <h1>Create</h1>
        <h4>HouseHold</h4>
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Greeting" class="control-label"></label>
                        <input asp-for="Greeting" class="form-control" />
                        <span asp-validation-for="Greeting" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Established" class="control-label" hidden></label>
                        <input type="hidden" asp-for="Established" class="form-control" value="@DateTime.Now" />
                        <span asp-validation-for="Established" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/HouseHolds/Dashboard.cshtml
@using Microsoft.AspNetCore.Identity
@model MVCFinApp.Models.ViewModels.HHDashboardVM
@inject UserManager<FAUser> UserManager
@inject MVCFinApp.Services.IHouseHoldService HouseHoldService
@{
    ViewData["Title"] = "Dashboard";
    var user = await UserManager.GetUserAsync(User);
    var script = TempData["Script"];
    var accounts = Model.Accounts;
}
<div class="row">
    <div class="col-md">
        <div class="row justify-content-between mt-3">
            <div class="col-md">
                <h1>@user.HouseHold.Name - Dashboard</h1>
            </div>
            <div class="col-auto pt-2">
                <div class="row">
                    <div class="col-auto pr-0">
                        @if (User.IsInRole("Administrator") || User.IsInRole("Head"))
                        {
                            <button class="btn btn-outline-secondary" data-toggle="modal" data-target="#inviteModal">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-plus"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><line x1="20" y1="8" x2="20" y2="14"></line><line x1="23" y1="11" x2="17" y2="11"></line></svg>
                                Invite
                            </button>
                        }
                        <button class="btn btn-outline-secondary" data-toggle="modal" data-target="#accountModal">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
                            Account
                        </button>
                        <button class="btn btn-outline-secondary" data-toggle="modal" data-target="#categoryModal">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
                            Category
                        </button>
                        <button class="btn btn-outline-secondary" data-toggle="modal" data-target="#itemModal">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
                            Item
                        </button>
                    </div>
                    <div class="col-auto pl-1">
                        <form asp-controller="HouseHolds" asp-action="Leave">
                            <button type="submit" class="btn btn-secondary">
                                Leave
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md">
                <button class="btn btn-success btn-lg" data-toggle="modal" data-target="#transactionModal">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-3"><path d="M12 20h9"></path><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path></svg>
                    <span class="ml-2">Transaction</span>
                </button>
            </div>
        </div>
        <div class="row mt-md-3">
            <div class="col-md widget p-3 mr-md-3 ml-md-3">
                <div class="row justify-content-between">
                    <div class="col-md">
                        <h4>Bank Accounts</h4>
                    </div>
                    <div class="col-md-auto">
                        <button class="btn btn-sm btn-outline-info p-1" data-toggle="modal" data-target="#historyModal">
                            History
                        </button>
                    </div>
                </div>
                <table class="table table-responsive-sm">
                    <thead>
                        <tr>
                            <td>Name</td>
                            <td>Balance</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var account in Model.Accounts)
                        {
                            <tr>
                                <td><a asp-controller="Transactions" asp-action="Transactions" asp-route-id="@account.Id">@account.Name</a></td>
                                <td>@account.CurrentBalance</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="col-md-4 widget p-3 mr-md-3">
                <canvas id="breakdownPieChart"></canvas>
            </div>
            <div class="col-md-5 widget p-3 mr-md-3">
                <canvas id="itemsBarChart"></canvas>
            </div>
        </div>
        <div class="row">
            <div class="col-md widget p-3 ml-md-3 mt-md-3 mb-md-3">
                <h3>Occupants of household</h3>
                <table class="table table-responsive-sm">
                    <thead>
                        <tr>
                            <td>Name</td>
                            <td>Email</td>
                            <td>Role</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var occupant in Model.Occupants)
                        {
                            <tr>
                                <td>@occupant.FullName</td>
                                <td>@occupant.Email</td>
                                <td>
                                    @await HouseHoldService.GetRoleAsync(occupant)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="col-md-8 widget p-3 m-md-3">
                <div class="row justify-content-between">
                    <div class="col-md">
                        <h3>Recent Transactions</h3>
                    </div>
                    <div class="col-md mr-3">
                        <div class="row justify-content-end">

                            <form asp-action="Dashboard" method="get">
                                <label for="years" class="mr-1 mt-1">Year</label>
                                <select id="years" name="year" class="form-control-sm mr-3" asp-items="ViewBag.Years"></select>

                                <label for="months" class="mr-1 mt-1">Month</label>
                                <select id="months" name="month" class="form-control-sm" asp-items="ViewBag.Months">
                                    <option value=@null selected>-- All --</option>
                                </select>
                            </form>

                        </div>
                    </div>
                </div>
                <table id="recentTransactions" class="table table-responsive-sm">
                    <thead>
                        <tr>
                            <td>Member</td>
                            <td>Account</td>
                            <td>Type</td>
                            <td>Amount</td>
                            <td>Date</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var transaction in Model.Transactions.OrderByDescending(t => t.Created))
                        {
                            <tr>
                                <td>@transaction.FAUser.FullName</td>
                                <td>@transaction.BankAccount.Name</td>
                                <td>@transaction.Type.ToString()</td>
                                <td>@transaction.Amount</td>
                                <td>@transaction.Created</td>
                                <td>
                                    <a class="btn btn-primary" asp-controller="Transactions" asp-action="Edit" asp-route-id="@transaction.Id">Edit</a>
                                    <a class="btn btn-primary"  asp-controller="Transactions" asp-action="Details" asp-route-id="@transaction.Id">Details</a>
                                    <a class="btn btn-danger" asp-controller="Transactions" asp-action="Delete" asp-route-id="@transaction.Id">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@await Html.PartialAsync("_InviteModalPartial", user)
@await Html.PartialAsync("_AccountModalPartial", user)
@await Html.PartialAsync("_CategoryModalPartial", user)
@await Html.PartialAsync("_ItemModalPartial")
@await Html.PartialAsync("_TransactionModalPartial")
@await Html.PartialAsync("_HistoryModalPartial", accounts)
@await Html.PartialAsync("_WizardPartial")

@section scripts {
    <script>
        @Html.Raw(script)
        BudgetBreakdownChart('@Url.Action("Categories", "Charts")');
        CategoryItemsChart('@Url.Action("Items", "Charts")');
    </script>
}

Views/HouseHolds/_WizardPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using MVCFinApp.Data.Enums
<div class="modal fade" id="wizardModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">

        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Set up your household</h3>
            </div>

            <div class="modal-body">
                <form id="accountSetup" asp-controller="HouseHolds" asp-action="SetUp" method="post">
                    <div id="wizard">
                        <h3>Bank</h3>
                        <section>
                            <div class="form-group">
                                <label for="bank" class="control-label">Name</label>
                                <input name="bank" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label for="accountType" class="control-label">Type</label>
                                <select name="accountType" asp-items="Html.GetEnumSelectList<AccountType>()" class="form-control"></select>
                            </div>
                            <div class="form-group">
                                <label for="startBalance" class="control-label">Balance</label>
                                <input name="startBalance" class="form-control" />
                            </div>
                        </section>
                        <h3>Category</h3>
                        <section>
                            <div class="form-group">
                                <label for="categoryName" class="control-label">Category Name</label>
                                <input name="categoryName" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label for="catDesc" class="control-label">Description</label>
                                <input name="catDesc" class="form-control" />
                            </div>
                        </section>
                        <h3>Item</h3>
                        <section>
                            <div class="form-group">
                                <label for="itemName" class="control-label">Item Name</label>
                                <input name="itemName" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label for="itemDesc" class="control-label">Description</label>
                                <input name="itemDesc" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label for="target" class="control-label">Budget</label>
                                <input name="target" class="form-control" />
                            </div>
                        </section>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>